// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	dto "assignment-golang-backend/dto"
	entity "assignment-golang-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// GetWalletById provides a mock function with given fields: id
func (_m *WalletRepository) GetWalletById(id int) (*entity.Wallet, error) {
	ret := _m.Called(id)

	var r0 *entity.Wallet
	if rf, ok := ret.Get(0).(func(int) *entity.Wallet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Topup provides a mock function with given fields: walletId, topUpAmt, sourceOfFundId, description
func (_m *WalletRepository) Topup(walletId int, topUpAmt int, sourceOfFundId int, description string) (*dto.TopUpResponseDto, error) {
	ret := _m.Called(walletId, topUpAmt, sourceOfFundId, description)

	var r0 *dto.TopUpResponseDto
	if rf, ok := ret.Get(0).(func(int, int, int, string) *dto.TopUpResponseDto); ok {
		r0 = rf(walletId, topUpAmt, sourceOfFundId, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TopUpResponseDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int, string) error); ok {
		r1 = rf(walletId, topUpAmt, sourceOfFundId, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: sourceWalletId, transferDto
func (_m *WalletRepository) Transfer(sourceWalletId int, transferDto *dto.TransferDto) (*dto.TransferDto, error) {
	ret := _m.Called(sourceWalletId, transferDto)

	var r0 *dto.TransferDto
	if rf, ok := ret.Get(0).(func(int, *dto.TransferDto) *dto.TransferDto); ok {
		r0 = rf(sourceWalletId, transferDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransferDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *dto.TransferDto) error); ok {
		r1 = rf(sourceWalletId, transferDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWalletRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletRepository(t mockConstructorTestingTNewWalletRepository) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
